/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PayFixationRecord = IDL.Record({
  'id' : IDL.Nat,
  'employeeName' : IDL.Text,
  'designation' : IDL.Text,
  'recordJson' : IDL.Text,
  'calculatedAt' : IDL.Int,
  'basicPayAtAppointment' : IDL.Nat,
  'employeeId' : IDL.Text,
  'dateOfAppointment' : IDL.Text,
  'fifthCpcScale' : IDL.Text,
  'department' : IDL.Text,
  'seventhCpcLevel' : IDL.Nat,
  'totalArrears' : IDL.Int,
  'sixthCpcPayBand' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'listRecords' : IDL.Func([], [IDL.Vec(PayFixationRecord)], ['query']),
  'saveRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PayFixationRecord = IDL.Record({
    'id' : IDL.Nat,
    'employeeName' : IDL.Text,
    'designation' : IDL.Text,
    'recordJson' : IDL.Text,
    'calculatedAt' : IDL.Int,
    'basicPayAtAppointment' : IDL.Nat,
    'employeeId' : IDL.Text,
    'dateOfAppointment' : IDL.Text,
    'fifthCpcScale' : IDL.Text,
    'department' : IDL.Text,
    'seventhCpcLevel' : IDL.Nat,
    'totalArrears' : IDL.Int,
    'sixthCpcPayBand' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'listRecords' : IDL.Func([], [IDL.Vec(PayFixationRecord)], ['query']),
    'saveRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };